baseURL = "https://kluctl.io/"
title = "kluctl.io"
enableRobotsTXT = true
enableGitInfo = true
# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"

enableInlineShortcodes = true

theme = "hextra"

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
section = [ "HTML", "RSS" ]

[languages.en]
languageName = "English"
weight = 1
title = "Hextra"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[[menu.main]]
identifier = "documentation"
name = "Documentation"
pageRef = "/docs"
weight = 1

[[menu.main]]
identifier = "showcase"
name = "Showcase"
pageRef = "/showcase"
weight = 2

[[menu.main]]
identifier = "blog"
name = "Blog"
pageRef = "/blog"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 4

[[menu.main]]
name = "Search"
weight = 5

  [menu.main.params]
  type = "search"

[[menu.main]]
name = "GitHub"
weight = 6
url = "https://github.com/imfing/hextra"

  [menu.main.params]
  icon = "github"

[[menu.sidebar]]
identifier = "more"
name = "More"
weight = 1

  [menu.sidebar.params]
  type = "separator"

[[menu.sidebar]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 2

[[menu.sidebar]]
identifier = "hugoDocs"
name = "Hugo Docs ↗"
url = "https://gohugo.io/documentation/"
weight = 3

[params]
description = "Modern, responsive, batteries-included Hugo theme for creating beautiful static websites."
displayUpdatedDate = true
dateFormat = "January 2, 2006"

  [params.navbar]
  displayTitle = true
  displayLogo = true
  width = "wide"

    [params.navbar.logo]
    path = "images/logo.svg"
    dark = "images/logo-dark.svg"

  [params.page]
  width = "normal"

  [params.theme]
  default = "system"
  displayToggle = true

  [params.footer]
  enable = true
  displayCopyright = true
  displayPoweredBy = true
  width = "normal"

  [params.search]
  enable = true
  type = "flexsearch"

    [params.search.flexsearch]
    index = "content"

  [params.editURL]
  enable = true
  base = "https://github.com/imfing/hextra/edit/main/exampleSite/content"

[params.blog.list]
displayTags = true

  # [params.comments]
  # enable = false
  # type = "giscus"

  #   [params.comments.giscus]
  #   repo = "imfing/hextra"
  #   repoId = "R_kgDOJ9fJag"
  #   category = "General"
  #   categoryId = "DIC_kwDOJ9fJas4CY7gW"
